[package]
name = "json_sizeoptimized_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true
test = false
doctest = false

[dependencies]
proc-macro2 = "1.0.39"
quote = "1.0.18"
syn = "1.0.95"
